# Generated by Django 5.1.15 on 2026-03-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.chapter'),
        ),
        migrations.AddField(
            model_name='bookpart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='books.bookpart'),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_job', to='books.book'),
        ),
        migrations.AddConstraint(
            model_name='bookpart',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_part_order'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('part', 'order'), name='unique_chapter_order'),
        ),
    ]
