# Generated by Django 5.1.15 on 2026-03-29 10:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Optional cover page PDF (A4, two 298pt-high images separated by white).', upload_to=books.models.Book._cover_upload_path),
        ),
    ]
