# Generated by Django 5.1.15 on 2026-03-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='doi',
            field=models.CharField(blank=True, help_text='Optional DOI link for this book.', max_length=200),
        ),
    ]
