# Generated by Django 5.1.15 on 2026-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_last_build_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='include_examples',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='include_solutions',
            field=models.BooleanField(default=True),
        ),
    ]
