# Generated by Django 5.1.15 on 2026-05-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_excluded_example_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_tail', models.TextField(blank=True)),
                ('build_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='books.buildjob')),
            ],
            options={
                'ordering': ['build_job_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('build_job', 'order'), name='unique_step_order_per_job')],
            },
        ),
    ]
