# Generated by Django 5.1.15 on 2026-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_buildstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildjob',
            name='preview_structure',
            field=models.BooleanField(default=False),
        ),
    ]
