# Generated by Django 5.1.15 on 2026-05-17 11:34

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_buildjob_preview_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def _migrate_both_to_all(apps, schema_editor):
        # Existing rows with last_build_format='both' meant "PDF + HTML".
        # The enum is replacing 'both' with 'all' (which adds EPUB).
        # Retroactively upgrading "both" to "all" gives those users the
        # superset on Retry — closest to their original intent.
        Book = apps.get_model('books', 'Book')
        Book.objects.filter(last_build_format='both').update(last_build_format='all')

    def _migrate_all_to_both(apps, schema_editor):
        Book = apps.get_model('books', 'Book')
        Book.objects.filter(last_build_format='all').update(last_build_format='both')

    operations = [
        migrations.AddField(
            model_name='book',
            name='epub_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='epub_path',
            field=models.CharField(blank=True, help_text='Filesystem path to the most recent EPUB output.', max_length=500),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='chapter_shas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='epub_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_build_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('epub', 'EPUB'), ('all', 'All formats (PDF + HTML + EPUB)')], default='pdf', help_text='Format selected for the most recent build; used by Retry.', max_length=8),
        ),
        migrations.RunPython(_migrate_both_to_all, _migrate_all_to_both),
        migrations.CreateModel(
            name='FrozenBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Human label (e.g. 'Fall 2026'). Shown next to the title.", max_length=200)),
                ('share_token', models.CharField(db_index=True, default=books.models._generate_share_token, max_length=64, unique=True)),
                ('title_snapshot', models.CharField(max_length=300)),
                ('author_snapshot', models.CharField(blank=True, max_length=200)),
                ('chapter_snapshot', models.JSONField(blank=True, default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('html_path', models.CharField(blank=True, max_length=500)),
                ('epub_path', models.CharField(blank=True, max_length=500)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_versions', to='books.book')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frozen_at'],
            },
        ),
    ]
