# Generated by Django 5.1.15 on 2026-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_epub_freeze_fields'),
    ]

    def _revert_all_to_both(apps, schema_editor):
        # 0011 converted legacy 'both' rows to 'all'. EPUB has since been
        # deferred from the 1.2 UI (tex4ebook + OpenChapters.sty are not
        # yet compatible), so we put those rows back to 'both' — that
        # matches what users actually want on Retry today.
        Book = apps.get_model('books', 'Book')
        Book.objects.filter(last_build_format='all').update(last_build_format='both')

    def _all_to_both_noop(apps, schema_editor):
        # No-op reverse: re-running 0011's both→all is not desirable on
        # rollback either; let an operator handle it manually if needed.
        pass

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_build_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('both', 'PDF + HTML'), ('epub', 'EPUB (experimental)'), ('all', 'All formats (PDF + HTML + EPUB, experimental)')], default='pdf', help_text='Format selected for the most recent build; used by Retry.', max_length=8),
        ),
        migrations.RunPython(_revert_all_to_both, _all_to_both_noop),
    ]
