# Generated by Django 5.1.15 on 2026-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('toc', models.JSONField(default=list)),
                ('cover_image_url', models.URLField(blank=True)),
                ('latex_entry_file', models.CharField(max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
