# Generated by Django 5.1.15 on 2026-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_subdir',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='github_repo',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('github_repo', 'chapter_subdir'), name='unique_chapter_in_repo'),
        ),
    ]
