# Generated by Django 5.1.15 on 2026-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_chapter_chapter_subdir_alter_chapter_github_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('topical', 'Topical')], default='topical', max_length=20),
        ),
    ]
