# Generated by Django 5.1.15 on 2026-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_chapter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chabbr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chapter',
            name='depends_on',
            field=models.JSONField(default=list),
        ),
    ]
