# Generated by Django 5.1.15 on 2026-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chabbr_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
