# Generated by Django 5.1.15 on 2026-04-01 13:29

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('github_repo', models.CharField(max_length=200)),
                ('github_src_path', models.CharField(default='src', max_length=200)),
                ('color_primary', models.CharField(default='#2563eb', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='chapter',
            name='authors',
            field=models.JSONField(default=list, validators=[catalog.models._validate_string_list]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='depends_on',
            field=models.JSONField(default=list, validators=[catalog.models._validate_string_list]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='keywords',
            field=models.JSONField(default=list, validators=[catalog.models._validate_string_list]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='toc',
            field=models.JSONField(default=list, validators=[catalog.models._validate_string_list]),
        ),
        migrations.AddField(
            model_name='chapter',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalog.discipline'),
        ),
    ]
