# Generated by Django 5.1.15 on 2026-04-01

from django.db import migrations


def create_mse_discipline(apps, schema_editor):
    """Create the initial MSE discipline and assign all existing chapters to it."""
    Discipline = apps.get_model("catalog", "Discipline")
    Chapter = apps.get_model("catalog", "Chapter")

    mse, _ = Discipline.objects.get_or_create(
        slug="mse",
        defaults={
            "name": "Materials Science and Engineering",
            "description": "Chapters covering materials science, crystallography, tensors, symmetry, and related topics.",
            "github_repo": "OpenChapters/OpenChapters",
            "github_src_path": "src",
            "color_primary": "#2563eb",
            "order": 0,
            "published": True,
        },
    )
    Chapter.objects.filter(discipline__isnull=True).update(discipline=mse)


def reverse_mse(apps, schema_editor):
    Chapter = apps.get_model("catalog", "Chapter")
    Chapter.objects.all().update(discipline=None)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_add_discipline"),
    ]

    operations = [
        migrations.RunPython(create_mse_discipline, reverse_mse),
    ]
