# Generated by Django 5.1.15 on 2026-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
