# Generated by Django 5.1.15 on 2026-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_reviewer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='html_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
