# Generated by Django 5.1.15 on 2026-04-17 17:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_html_built_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=500)),
                ('html_node', models.CharField(max_length=100)),
                ('anchor', models.CharField(blank=True, max_length=200)),
                ('text_content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='catalog.chapter')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_cha_search__95ce31_gin'), models.Index(fields=['chapter'], name='catalog_cha_chapter_03263b_idx')],
            },
        ),
    ]
