# Generated by Django 5.1.15 on 2026-05-08 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_search_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_tex', models.TextField()),
                ('solution_tex', models.TextField()),
                ('difficulty', models.CharField(choices=[('introductory', 'Introductory'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', max_length=16)),
                ('license', models.CharField(default='CC BY-NC-SA 4.0', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('preview_built_at', models.DateTimeField(blank=True, null=True)),
                ('preview_build_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examples', to=settings.AUTH_USER_MODEL)),
                ('chapters', models.ManyToManyField(related_name='examples', to='catalog.chapter')),
                ('primary_chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_examples', to='catalog.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='catalog_exa_status_898a89_idx'), models.Index(fields=['status', 'primary_chapter'], name='catalog_exa_status_c0ecdc_idx')],
            },
        ),
    ]
