# Generated by Django 5.1.15 on 2026-05-09 10:56

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=catalog.models._example_figure_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='catalog.example')),
            ],
            options={
                'ordering': ['example_id', 'order', 'id'],
                'indexes': [models.Index(fields=['example'], name='catalog_exa_example_637fb3_idx')],
            },
        ),
    ]
