# Generated by Django 5.1.15 on 2026-05-09 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_examplefigure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='example',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('author', 'slug'), name='unique_example_slug_per_author'),
        ),
    ]
