# Generated by Django 5.1.15 on 2026-05-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_example_slug_example_unique_example_slug_per_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.example')),
            ],
            options={
                'ordering': ['example_id', 'version_no'],
                'indexes': [models.Index(fields=['example', '-version_no'], name='catalog_exa_example_67c991_idx')],
                'constraints': [models.UniqueConstraint(fields=('example', 'version_no'), name='unique_example_version_no')],
            },
        ),
    ]
