# Generated by Django 5.1.15 on 2026-06-05 14:12

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_exampleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='related_to',
            field=models.JSONField(default=list, validators=[catalog.models._validate_string_list]),
        ),
    ]
