# Generated by Django 5.1.15 on 2026-06-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_chapter_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='concept_doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ChapterDOIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_versions', to='catalog.chapter')),
            ],
            options={
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'version'), name='unique_chapter_version_doi')],
            },
        ),
    ]
