# Generated by Django 5.1.15 on 2026-05-13 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_audit_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splash_enabled', models.BooleanField(default=False)),
                ('splash_duration_ms', models.PositiveIntegerField(default=10000, help_text='Auto-dismiss timer in milliseconds (2000–60000).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(60000)])),
                ('splash_image', models.ImageField(blank=True, help_text='Leave blank to use the bundled placeholder SVG.', null=True, upload_to='splash/')),
                ('splash_caption', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
